---
# configure apt-cacher-ng (as a client) if aptcacher.yml is provided
# check: http://stackoverflow.com/questions/30674958/ansible-include-vars-continue-if-file-not-found
- include_vars: "{{ item }}"
  with_first_found:
   - aptcacher.yml
   - empty_fallback.yml
  tags: install

- name: define timestamp variable (for backups)
  command: date +%Y%m%d-%H%M%S
  register: timestamp
  tags: backup

- name: use apt-cache
  template: src=01_proxy.j2 dest=/etc/apt/apt.conf.d/01_proxy owner=root group=root mode=644
  sudo: true
  when: aptcacher_host is defined
  tags: install

# install base applications
- name: install base applications
  apt: "pkg={{item}} state=installed update_cache=yes"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - ntp
    - openjdk-7-jdk
    - openjdk-7-jre
    - openssh-server
    # optional utilities
    - tree
    - vim
  tags: install

- name: correct java version selected
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  tags: install

# start necessary services
- name: start the ntp service
  service: name=ntp state=started enabled=true
  tags: install

# scripts related
- name: create scripts_dir
  file: "path={{ scripts_dir }} state=directory mode=0777"
  tags:
    - install
    - backup
    - restore

- name: copy functions.sh
  copy: "src=functions.sh dest={{ scripts_dir }}/functions.sh mode=0755"
  tags:
    - install
    - backup
    - restore

- name: copy get_newest_file.sh
  template: "src=get_newest_file.sh.j2 dest={{ scripts_dir }}/get_newest_file.sh mode=0755"
  tags:
    - install
    - backup
    - restore

################################################################################
# backup
################################################################################

# setup backup folder & stop service
- name: create backup folder
  file: "path={{ backup_dir_common }} state=directory mode=0777"
  tags: backup

# backup jenkins
- name: "backup jenkins"
  command: "tar -cf {{ backup_dir_common }}/{{ timestamp.stdout }}_{{ ssh_backup_filename }} -C / /etc/ssh"
  tags: backup

################################################################################
# restore
################################################################################

# restore jenkins
- name: "restore commons - find latest backup"
  command: "{{ scripts_dir }}/get_newest_file.sh {{ backup_dir_common }} {{ ssh_backup_filename }}"
  register: backup_file
  ignore_errors: True
  tags: restore

- name: "restore {{ jenkins_home_dir }} - untar backup"
  unarchive: src={{ backup_dir_common }}/{{ backup_file.stdout }} dest=/ copy=no
  when: backup_file|success
  tags: restore