---
  sonar_user: sonar
  sonar_group: adm

  sonar_db_name: sonar
  sonar_db_user: sonar
  sonar_db_pass: sonar

  sonar_dir: /opt/sonar

  sonar_backup_db_filename: dump.sql.gz
  sonar_backup_conf_filename: opt-sonar-conf.tar
  sonar_backup_plugins_filename: opt-sonar-extentions-plugins.tar