---
# add specified repository into sources list
- name: add apt-repository for jenkins (deb)
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  tags: install

- name: add apt-key for jenkins
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  tags: install

# install jenkins
- name: install jenkins
  apt: "pkg={{ item }} state=installed update_cache=yes"
  with_items:
    - jenkins
  tags: install

# configure jenkins
- name: configure jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins owner=root group=root mode=755
  notify: restart jenkins
  tags: install

# add necessary plugins
# https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin
- name: add jenkins plugin - git
  get_url: url=http://updates.jenkins-ci.org/latest/git.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/SCM+API+Plugin
- name: add jenkins plugin - scm-api (git dependency)
  get_url: url=http://updates.jenkins-ci.org/latest/scm-api.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/Git+Client+Plugin
- name: add jenkins plugin - git-client
  get_url: url=http://updates.jenkins-ci.org/latest/git-client.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Hook+Plugin
- name: add jenkins plugin - gitlab-hook
  get_url: url=http://updates.jenkins-ci.org/latest/gitlab-hook.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/Ruby+Runtime+Plugin
- name: add jenkins plugin - ruby-runtime (gitlab-hook dependency)
  get_url: url=http://updates.jenkins-ci.org/latest/ruby-runtime.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Logo+Plugin
- name: add jenkins plugin - gitlab-logo
  get_url: url=http://updates.jenkins-ci.org/latest/gitlab-logo.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/GitLab+Plugin
- name: add jenkins plugin - gitlab-plugin
  get_url: url=http://updates.jenkins-ci.org/latest/gitlab-plugin.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Merge+Request+Builder+Plugin
- name: add jenkins plugin - gitlab-merge-request-jenkins
  get_url: url=http://updates.jenkins-ci.org/latest/gitlab-merge-request-jenkins.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

# http://docs.sonarqube.org/display/PLUG/Jenkins+Plugin
- name: add jenkins plugin - sonar
  get_url: url=http://updates.jenkins-ci.org/latest/sonar.hpi dest=/var/lib/jenkins/plugins owner=jenkins group=jenkins mode=644
  notify: restart jenkins
  tags: install

################################################################################
# backup
################################################################################

# setup backup folder & stop service
- name: create backup folder
  file: "path={{ backup_dir_jenkins }} state=directory mode=0777"
  tags: backup

- name: stop jenkins
  service: name=jenkins state=stopped
  tags: backup

# backup jenkins
- name: "backup jenkins"
  command: "tar -cf {{ backup_dir_jenkins }}/{{ timestamp.stdout }}_{{ jenkins_backup_filename }} -C / {{ jenkins_home_dir }}"
  notify: start jenkins
  tags: backup

# remove duplicated backups
- name: remove duplicated backups
  command: "fdupes -dN {{ backup_dir_jenkins }}"
  tags: backup

################################################################################
# restore
################################################################################

# stop service
- name: stop jenkins
  service: name=jenkins state=stopped
  tags: backup

# restore jenkins
- name: "restore jenkins - find latest backup"
  command: "{{ scripts_dir }}/get_newest_file.sh {{ backup_dir_jenkins }} {{ jenkins_backup_filename }}"
  register: backup_file
  ignore_errors: True
  tags: restore

- name: "restore {{ jenkins_home_dir }} - untar backup"
  unarchive: src={{ backup_dir_jenkins }}/{{ backup_file.stdout }} dest=/ copy=no
  notify: start jenkins
  when: backup_file|success
  tags: restore